//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm_Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDataEntities : DbContext
    {
        public MyDataEntities()
            : base("name=MyDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tCliente> tCliente { get; set; }
        public virtual DbSet<tDitte> tDitte { get; set; }
        public virtual DbSet<tPreventiveDetails> tPreventiveDetails { get; set; }
        public virtual DbSet<tProdoct> tProdoct { get; set; }
        public virtual DbSet<tProva> tProva { get; set; }
    }
}
