//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tClienti
    {
        public int IdCliente { get; set; }
        public string RagioneSociale { get; set; }
        public string CodiceUniklima { get; set; }
        public string Indirizzo { get; set; }
        public Nullable<double> CAP { get; set; }
        public string Citta { get; set; }
        public string Provincia { get; set; }
    }
}
