//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDitte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tDitte()
        {
            this.tListini = new HashSet<tListini>();
        }
    
        public int idDitta { get; set; }
        public string NomeDitta { get; set; }
        public string RagioneSocialeDitta { get; set; }
        public string IndirizzoDitta { get; set; }
        public string CapDitta { get; set; }
        public string CittaDitta { get; set; }
        public string ProvinciaDitta { get; set; }
        public string TelefonoDitta { get; set; }
        public string FaxDitta { get; set; }
        public string URLDitta { get; set; }
        public string e_mailDitta { get; set; }
        public string PIvaDitta { get; set; }
        public string CodiceAgente { get; set; }
        public string Listino { get; set; }
        public string Logo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tListini> tListini { get; set; }
    }
}
