//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPreventive
    {
        public int ID { get; set; }
        public Nullable<double> ScontoGenerale { get; set; }
        public Nullable<double> ImportoTotaleScontato { get; set; }
        public Nullable<double> TotalearticoliListino { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Durata { get; set; }
    }
}
