//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tUser()
        {
            this.tShift = new HashSet<tShift>();
        }
    
        public int idUser { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<bool> IsAvaible { get; set; }
    
        public virtual tRole tRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tShift> tShift { get; set; }
    }
}
